const BAD_REQUEST = 400;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const UNAUTHORIZED = 401;
const INTERNAL_SERVER_ERROR = 500;
const CREATED = 201;
const SUCCESS = 200;
const CONFLICT = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  SUCCESS,
  CREATED,
  CONFLICT,
  FORBIDDEN,
  UNAUTHORIZED,
};
